trek:	abandon.o attack.o autover.o capture.o checkcond.o check_out.o compkl.o computer.o damage.o damaged.o dcrept.o destruct.o dock.o dumpgame.o dumpme.o dumpssradio.o events.o externs.o getcodi.o getpar.o help.o impulse.o initquad.o kill.o klmove.o lose.o lrscan.o main.o move.o nova.o out.o phaser.o play.o ram.o ranf.o rest.o schedule.o score.o setup.o setwarp.o shield.o snova.o srscan.o systemname.o torped.o visual.o warp.o win.o
	cc -o trek abandon.o attack.o autover.o capture.o checkcond.o check_out.o compkl.o computer.o damage.o damaged.o dcrept.o destruct.o dock.o dumpgame.o dumpme.o dumpssradio.o events.o externs.o getcodi.o getpar.o help.o impulse.o initquad.o kill.o klmove.o lose.o lrscan.o main.o move.o nova.o out.o phaser.o play.o ram.o ranf.o rest.o schedule.o score.o setup.o setwarp.o shield.o snova.o srscan.o systemname.o torped.o visual.o warp.o win.o -lm

abandon.o:	abandon.c trek.h
	cc -c -o abandon.o abandon.c

attack.o:	attack.c trek.h
	cc -c -o attack.o attack.c

autover.o:	autover.c trek.h
	cc -c -o autover.o autover.c

capture.o:	capture.c trek.h
	cc -c -o capture.o capture.c

checkcond.o:	checkcond.c trek.h
	cc -c -o checkcond.o checkcond.c

check_out.o:	check_out.c trek.h
	cc -c -o check_out.o check_out.c

compkl.o:	compkl.c trek.h
	cc -c -o compkl.o compkl.c

computer.o:	computer.c trek.h getpar.h
	cc -c -o computer.o computer.c

damage.o:	damage.c trek.h
	cc -c -o damage.o damage.c

damaged.o:	damaged.c trek.h
	cc -c -o damaged.o damaged.c

dcrept.o:	dcrept.c trek.h
	cc -c -o dcrept.o dcrept.c

destruct.o:	destruct.c trek.h getpar.h
	cc -c -o destruct.o destruct.c

dock.o:	dock.c trek.h
	cc -c -o dock.o dock.c

dumpgame.o:	dumpgame.c trek.h
	cc -c -o dumpgame.o dumpgame.c

dumpme.o:	dumpme.c trek.h
	cc -c -o dumpme.o dumpme.c

dumpssradio.o:	dumpssradio.c trek.h
	cc -c -o dumpssradio.o dumpssradio.c

events.o:	events.c trek.h getpar.h
	cc -c -o events.o events.c

externs.o:	externs.c trek.h
	cc -c -o externs.o externs.c

getcodi.o:	getcodi.c trek.h getpar.h
	cc -c -o getcodi.o getcodi.c

getpar.o:	getpar.c trek.h getpar.h
	cc -c -o getpar.o getpar.c

help.o:	help.c trek.h
	cc -c -o help.o help.c

impulse.o:	impulse.c trek.h getpar.h
	cc -c -o impulse.o impulse.c

initquad.o:	initquad.c trek.h
	cc -c -o initquad.o initquad.c

kill.o:	kill.c trek.h
	cc -c -o kill.o kill.c

klmove.o:	klmove.c trek.h
	cc -c -o klmove.o klmove.c

lose.o:	lose.c trek.h getpar.h
	cc -c -o lose.o lose.c

lrscan.o:	lrscan.c trek.h
	cc -c -o lrscan.o lrscan.c

main.o:	main.c trek.h getpar.h
	cc -c -o main.o main.c

move.o:	move.c trek.h
	cc -c -o move.o move.c

nova.o:	nova.c trek.h
	cc -c -o nova.o nova.c

out.o:	out.c trek.h
	cc -c -o out.o out.c

phaser.o:	phaser.c trek.h getpar.h
	cc -c -o phaser.o phaser.c

play.o:	play.c trek.h getpar.h
	cc -c -o play.o play.c

ram.o:	ram.c trek.h
	cc -c -o ram.o ram.c

ranf.o:	ranf.c trek.h
	cc -c -o ranf.o ranf.c

rest.o:	rest.c trek.h getpar.h
	cc -c -o rest.o rest.c

schedule.o:	schedule.c trek.h
	cc -c -o schedule.o schedule.c

score.o:	score.c trek.h getpar.h
	cc -c -o score.o score.c

setup.o:	setup.c trek.h getpar.h
	cc -c -o setup.o setup.c

setwarp.o:	setwarp.c trek.h getpar.h
	cc -c -o setwarp.o setwarp.c

shield.o:	shield.c trek.h getpar.h
	cc -c -o shield.o shield.c

snova.o:	snova.c trek.h
	cc -c -o snova.o snova.c

srscan.o:	srscan.c trek.h getpar.h
	cc -c -o srscan.o srscan.c

systemname.o:	systemname.c trek.h
	cc -c -o systemname.o systemname.c

torped.o:	torped.c trek.h getpar.h
	cc -c -o torped.o torped.c

visual.o:	visual.c trek.h getpar.h
	cc -c -o visual.o visual.c

warp.o:	warp.c trek.h getpar.h
	cc -c -o warp.o warp.c

win.o:	win.c trek.h getpar.h
	cc -c -o win.o win.c

clean:
	rm -f trek abandon.o attack.o autover.o capture.o checkcond.o check_out.o compkl.o computer.o damage.o damaged.o dcrept.o destruct.o dock.o dumpgame.o dumpme.o dumpssradio.o events.o externs.o getcodi.o getpar.o help.o impulse.o initquad.o kill.o klmove.o lose.o lrscan.o main.o move.o nova.o out.o phaser.o play.o ram.o ranf.o rest.o schedule.o score.o setup.o setwarp.o shield.o snova.o srscan.o systemname.o torped.o visual.o warp.o win.o
