# crude makefile ain't done yet -uso.
mail:	cmd1.c cmd2.c cmd3.c cmdtab.c collect.c dotlock.c edit.c fio.c getname.c head.c lex.c list.c main.c names.c popen.c quit.c send.c strings.c support.c temp.c tty.c v7.local.c vars.c version.c
	$(CC) -o mail cmd1.c cmd2.c cmd3.c cmdtab.c collect.c dotlock.c edit.c fio.c getname.c head.c lex.c list.c main.c names.c popen.c quit.c send.c strings.c support.c temp.c tty.c v7.local.c vars.c version.c
