#!/bin/bash
#
# Copyright (C) 2006-2020 Chris Webb.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
#  * The above copyright notice and this permission notice shall be included 
#    in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING  
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

set -o pipefail
shopt -s dotglob extglob nullglob

export PATH=/bin
hostname example

mount -a -n -t proc
mount -a -n -t cgroup2,devtmpfs,sysfs,tmpfs
mkdir -p /dev/pts && mount -a -n -t devpts
mkdir -m 0755 -p /run/empty
mkdir -m 1777 -p /run/lock /run/shm

ln -f -n -s /proc/self/fd /dev/fd
ln -f -n -s fd/0 /dev/stdin
ln -f -n -s fd/1 /dev/stdout
ln -f -n -s fd/2 /dev/stderr

mount -n -o remount,ro /
fsck -a -A -P -T >/dev/null || [[ $? -le 1 ]] || exec bash
mount -o remount,rw /
mount -a -t nonfs
swapon -a -e

ip link set lo up
ip link set eth0 up
ip address add 192.168.1.2/24 dev eth0
ip route add default via 192.168.1.1

[[ -d /var/log ]] && syslogd -s
[[ -f /etc/ssh/sshd_config ]] && ssh-keygen -A && $(type -P sshd)

# Start other daemons here

[[ -r /dev/initctl ]] || mkfifo -m 0600 /dev/initctl
ctrlaltdel soft && trap reboot INT
while read -d '' -r MESSAGE; do
  [[ $MESSAGE == @(halt|poweroff|reboot) ]] && break
  [[ ${MESSAGE%% *} == run ]] && eval "${MESSAGE#run }"
done <>/dev/initctl

# Gracefully shut down daemons here

kill -TERM -1 && sleep 5 && kill -KILL -1
swapoff -a
umount -a -r -t nodevtmpfs,noproc,noramfs,nosysfs,notmpfs
exec stop "$MESSAGE"
